name: Hourly ResetBot Trigger

on:
  schedule:
    # запуск каждый час, 0‑я минута (UTC)
    - cron: '0 * * * *'
  workflow_dispatch:  # запуск вручную из вкладки Actions

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger send_lessons endpoint
        run: |
          curl -s -X GET "https://fonten1985.pythonanywhere.com/trigger_lessons"
